module.exports = [
  {
    ignores: [
      "backup_pre_local_mode/**",
      "user_data/**",
      "coverage/**",
      ".git/**",
      "node_modules/**",
    ],
  },
  {
    files: ["server/**/*.js", "script_test/**/*.js", "tests/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        require: "readonly",
        module: "readonly",
        __dirname: "readonly",
        process: "readonly",
        console: "readonly",
        fetch: "readonly",
        AbortController: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-redeclare": "error",
      "no-unreachable": "error",
      "no-constant-condition": ["error", { checkLoops: false }],
    },
  },
  {
    files: ["tools/**/*.mjs"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        process: "readonly",
        console: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-redeclare": "error",
      "no-unreachable": "error",
      "no-constant-condition": ["error", { checkLoops: false }],
    },
  },
  {
    files: ["public/js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        localStorage: "readonly",
        indexedDB: "readonly",
        URL: "readonly",
        Blob: "readonly",
        Intl: "readonly",
        fetch: "readonly",
        console: "readonly",
        URLSearchParams: "readonly",
        HTMLElement: "readonly",
        getComputedStyle: "readonly",
        Audio: "readonly",
        navigator: "readonly",
        module: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        crypto: "readonly",
        confirm: "readonly",
        loadData: "readonly",
        saveData: "readonly",
        initStorage: "readonly",
        generateId: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-redeclare": "off",
      "no-unreachable": "error",
      "no-constant-condition": ["error", { checkLoops: false }],
    },
  },
];
